CREATE TABLE ORDERITEMS(
  ORDERITEM_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
  ITEM_ID INT(10) UNSIGNED,
  QUANTITY INT(10) DEFAULT 0,
  DELIVERY_DATE DATE,
  FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID)
);