DROP TABLE ITEMS_ON_ORDER;

CREATE TABLE ITEMS_ON_ORDER (
  IOO_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID INT(10) UNSIGNED NOT NULL,
  ITEM_ID INT(10) UNSIGNED NOT NULL,

  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
  FOREIGN KEY (ITEM_ID) REFERENCES ORDERITEMS (ORDERITEM_ID)
)